### ISSUE TITLE
Get rid of the proxy

### ISSUE THREAD

**Issue by IKatsu** [piero-la-lune/FSE-Planner#28]
Trying to get FSE Planner going on a Linux machine (Apache) because I just happen to have one of those running on my LAN but I can't get it to work.
Both the release file and a git clone with npm build give the same error when trying to pull data from FSE.
From what I can tell it's not actually trying to connect either and there are no errors in the browser debug console.

I did notice that while doing npm build it complains about an optional package 'fsevents' which is a MAC only package.
Not sure if FSE-Planner only runs on a mac ?

**Comment by piero-la-lune** [comment]
Should be working... I am running Windows (and Linux server), nothing to do with MAC...

1. What browser are you using to access the app? Does it work when you load data with this browser using the main website (https://piero-la-lune.fr/fseplanner/)?
2. Could you share the exact output you get when running `npm build`
3. Could you:
       a. Open the Developer Tools in your browser, go to the Network tab
       b. Try loading data (you should get the error)
       c. Check the Network tab, you should see an outgoing GET request to piero-la-lune.fr => can you share a screen of the Network tab?

**Comment by IKatsu** [comment]
I have the whole build log ready but when checking the requests from the debug screen i noticed it is trying to query 'https://piero-la-lune.fr/fseplanner/proxy/data?userkey=etc' instead of the FSE server and getting a 404 not found.

Still need the build log after that one ?

**Comment by piero-la-lune** [comment]
Ok, I get what is happening.

Because of the Cross-Origin header not being correctly set on FSE servers, the browser cannot directly interrogate FSE (you get a cross-origin error).

That is why I had to implement a proxy on my server, and route all requests through this proxy. I configured it so it would only accept requests from users using the https://piero-la-lune.fr/fseplanner/ instance. That is why you are getting a 404 error. FYI, my nginx proxy configuration:

```
location /fseplanner/proxy {

        if ($http_origin !~* "(^null$|^$|^https?://(piero-la-lune.fr|localhost:3000)$)") {
                return 404;
        }

        rewrite ^/fseplanner/proxy/(.*)$ /$1 break;

        # Activer le proxy
        proxy_set_header                X-Real-IP $remote_addr;
        proxy_set_header                X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_pass                      https://server.fseconomy.net;
        proxy_redirect                  off;
        proxy_buffers                   32 16k;
        proxy_busy_buffers_size         64k;

        # Ajouter les headers de contrôle d'accès CORS
        add_header    'Access-Control-Allow-Origin' "$http_origin" always;
        add_header    'Access-Control-Allow-Methods' 'GET' always;
        add_header    'Access-Control-Allow-Headers' 'Origin, X-Requested-With, Content-Type, Accept' always;
        add_header    'Access-Control-Allow-Credentials' 'true' always;
}
```

My bad, I should have stated in the README that you need to configure your own proxy to make it work.

You have to options:
* Simpler - use my proxy: just give me the DNS/IP you are using to access your own instance, I will whitelist it
* Better - use your own proxy: before building the app, you have to change the variable `REACT_APP_PROXY` in the `.env` file, and set up your own proxy in Apache (or use another existing one, such as https://cors-anywhere.herokuapp.com/)

**Comment by IKatsu** [comment]
I'll see if i can set up my own proxy.
Tried giving the FSE people a poke about their header ?

**Comment by piero-la-lune** [comment]
I asked, we will see what happens...

https://www.fseconomy.net/forum/feature-request/127259-cors-headers-for-datafeeds

**Comment by piero-la-lune** [comment]
Thanks to airboss, the correct HTTP headers have been added to the FSE datafeeds, and the proxy is no longer required
