### ISSUE TITLE
Suggestion for route finding

### ISSUE THREAD

**Issue by jonasbeaver** [piero-la-lune/FSE-Planner#35]
It would be great to search for a particular rentable plane, and find the longest/shortest/highest income/best route for that plane.

For example, today I'd like to fly the Baron somewhere in Canada. I could search airports that have the Baron available for rent, then search only those airports for routes. Then be able to choose the best route available using that plane, or at least a visual representation of good possible routes?

If you are only searching for routes from airports that have a particular airplane for rent, is it possible to keep the data request only to airports where that aircraft is available for rent (and keep the data quantity and requests lower, or increase the search area without data size penalties)?

This is a fantastic tool already, thank you for your work!

**Comment by piero-la-lune** [comment]
I believe you should already be able to achieve what you are suggesting:

1. Load all Barons available for rent
2. Pick a location you want to fly from (where a Baron can be rented)
3. If not already done, load jobs in the vicinity
4. Launch the Route Finder: you have to select "Free Search" and enter the ICAO where the plane is available as your starting point (no need to enter a destination)

![image](https://user-images.githubusercontent.com/614507/107827585-56405000-6d87-11eb-9289-6a5fd736bd17.png)


It is not really possible to limit the data requests to only airports where an aircraft is available for rent, because the tool would not know which other airports to load as possible second/third/etc. hop. You need to load a large enough area around the starting point to be sure to analyze all possible routes. I would recommend choosing a starting point, and only then loading jobs in the area, to avoid having to load a whole continent.

**Comment by piero-la-lune** [comment]
I believe what you are asking may already be possible:

1. Load all Baron available for rent
2. Load jobs in Canada
3. Launch Route Finder (ensure you select "rent a plane", it will only consider all airports with a Baron available for rent as a starting point)

It is not really possible to limit the data requests to only airports where an aircraft is available for rent, because the tool would not know which other airports to load as possible second/third/etc. hop. You need to load a large enough area around the starting point to be sure to analyze all possible routes. Canada should remain a not too large area to load jobs from.


It is not really possible to limit the data requests to only airports where an aircraft is available for rent, because the tool would not know which other airports to load as possible second/third/etc. hop. You need to load a large enough area around the starting point to be sure to analyze all possible routes. I would recommend choosing a starting point, and only then loading jobs in the area, to avoid having to load a whole continent.

**Comment by piero-la-lune** [comment]
@jonasbeaver: did my answer help? Or do you feel there is still room for improvement on the tool (if so, could you explain?) ?

**Comment by jonasbeaver** [comment]
Your answer did help, I was failing because I was trying to do a route search just by downloading it and running it from my own computer instead of putting it on a server and using it right. After trying the one you are hosting on your website I learned your planner does exactly what I had asked for. It is very good!

**Comment by piero-la-lune** [comment]
Great, thanks! (indeed, the app does require to be hosted on a server for the route planner to work, but all other functionalities should work on your own computer)

**Comment by jonasbeaver** [comment]
but... if I do have this thread as a bit of a wish list:

In the filters is min/max duration for total flight time for the whole route or per leg, and would it be possible to have a total flight time min/max for the whole trip and a max leg distance filter for the whole trip?

I've been making a ton of money with the CJ4 and Citation Longitude in MSFS, mostly because of this tool you have created!

I will usually select a number of middle eastern countries, eastern and northern europe, and russia as my regions to job search, select the CJ4 as the rentable airplane, and see what comes up. The reason I ask is if I filter by best pay per flight time or per mile almost always ends up with a 48nm trip for ~$4k which is not what I'm trying to do. Doing this search, I usually get routes with a total pay ~50-70k varying between 7-12 hours flight time with the CJ4 parameters set to 10 passengers and 1500kg. So far, I have been filtering by total pay and checking total flight times. In the example today, the suggested routes are between 10.5 and 14 hours (~3000nm). If I could filter so the total leg distance didn't exceed the range of the plane (which I believe I can set now in the filter) AND the total overall flight distance could be limited to my choice (say 12 hours, or no more than 3000nm for the entire trip) I could fine tune my selections better. What I am currently doing is sorting by Total Pay, and finding the shortest timed trip within a few thousand dollars of best pay. The best trip today for total pay is $77205 and 12h11. There is another trip at $73647 but its only 10h58. If I could filter for best pay per mile but only on trips over 10 hours for the total flight for example I think I could better choose the route to fly. I could also find the best 5 hour routes that way.

Another thing I'm up to is, I'm trying to get a DA62 from europe to north america, and this route planner has been excellent for that. It would be useful to have in the free search not just the airport you are starting and ending from, but if it was possible to force an intermediate stop. I wanted very much to go through Vagar in the Faroe Islands on my way to Iceland (I've made it to Keflavik already and because of your planner I did it +$24k instead of paying to ferry or trying to find my own routes). There were trips to and from it along the route, but I couldn't get the route finder to include it. That said, the flight planner is EXCELLENT for manually choosing your legs as well, it just takes some observation and clicking.

One other area I still find myself looking for alternative resources away from your flight planner is finding alternative airports when FSE and MSFS databases are not the same. Currently I am using this: https://fse-aardvark-planner.co.uk/msfs-icaos/ to find the best alternative airport when it doesn't exist in MSFS. Your planner will let me know an FSE airport doesn't exist, and lists multiple alternatives, but the link I sent you shows a green box of the region in which to land for it to count as the FSE listed airport AND all the airports (if there are any) which would be acceptable as alternative landing airports. Your planner is already good in this respect, but it could be a little better. This is a fairly rare circumstance, but flying in the middle east and russia (that's where the big bucks are in FSE) its a bit more common.

Please note, these are not bugs or complaints, I am using your tool almost every day now (if you see a lot of hits on your site from Texas thats me!). It is very quickly coming to the point where I don't do a flight without using your planner first.

Thank you!

btw If you had a flight sim that has a citation mustang in it, and you'd like one for FSE, I bought one by accident and would be happy to sell it to you for what I paid for it :)

**Comment by jonasbeaver** [comment]
lol, I was writing it as you closed it!

**Comment by piero-la-lune** [comment]
oops sorry :)
