### ISSUE TITLE
Feature - Links to ChartFox or SkyVector

### ISSUE THREAD

**Issue by oobayly** [piero-la-lune/FSE-Planner#81]
It would be handy to have links to the airports info page on ChartFox or SkyVector. This way you can check the airport info while planning your flight to unfamiliar airports).
The links are _generally_ easy to predict from the ICAO codes (there are some outliers where the ICAO code has changed). 
[Oxford Kidlington - ChartFox - https://chartfox.org/EGTK](https://chartfox.org/EGTK)
[Oxford Kidlington - SkyVector - https://skyvector.com/airport/EGTK](https://skyvector.com/airport/EGTK)

The only concern I can see is the problem of cluttering up the context menu, but it could be added as a user configurable option.

If you'd like, I could try putting a PR together.

**Comment by piero-la-lune** [comment]
It is something I had considered, but did not pursue, because I did not know which services to add (I am new to flight sim, but I feel like each user has its own favorite service(s)), and I wanted to limit myself to only one or two max. Sky Vector seems a good bet. I do not know Chartfox.

Feel free to submit a PR, we could integrate these two services for the time being, and if some users request other services, I will look into configurable options.

**Comment by oobayly** [comment]
I only came across ChartFox recently when working on the AviTab plugin. It does need an VatSim account, but they'e done a fantastic job gathering AIPs from a large range of countries - https://chartfox.org/

**Comment by piero-la-lune** [comment]
Implemented thanks to @oobayly
